import os


class Settings:
    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)


def load_settings() -> Settings:
    JWT_ALG = os.getenv("JWT_ALG", "RS256")
    JWT_USER_ID_CLAIM = os.getenv("JWT_USER_ID_CLAIM", "user_id")
    JWT_PUBLIC_KEY = os.getenv("JWT_PUBLIC_KEY", "")
    JWT_PUBLIC_KEY_FILE = os.getenv("JWT_PUBLIC_KEY_FILE", "")
    JWT_JWKS_URL = os.getenv("JWT_JWKS_URL", "")
    JWT_ISSUER = os.getenv("JWT_ISSUER", "")
    JWT_AUDIENCE = os.getenv("JWT_AUDIENCE", "")
    JWT_LEEWAY = int(os.getenv("JWT_LEEWAY", "0"))
    WS_MODE = os.getenv("WS_MODE", "terminator")
    EVENTS_MODE = os.getenv("EVENTS_MODE", "")
    if not EVENTS_MODE:
        EVENTS_MODE = "broker" if WS_MODE == "core" else "webhook"
    EVENTS_MODE = EVENTS_MODE.lower()
    if EVENTS_MODE not in ("broker", "webhook", "both", "none"):
        EVENTS_MODE = "broker" if WS_MODE == "core" else "webhook"
    SYMFONY_WEBHOOK_URL = os.getenv("SYMFONY_WEBHOOK_URL", "")
    SYMFONY_WEBHOOK_SECRET = os.getenv("SYMFONY_WEBHOOK_SECRET", "")
    GATEWAY_API_KEY = os.getenv("GATEWAY_API_KEY", "")
    REDIS_DSN = os.getenv("REDIS_DSN", "")
    REDIS_STREAM = os.getenv("REDIS_STREAM", "ws.outbox")
    RABBITMQ_DSN = os.getenv("RABBITMQ_DSN", "")
    RABBITMQ_QUEUE = os.getenv("RABBITMQ_QUEUE", "ws.outbox")
    RABBITMQ_EXCHANGE = os.getenv("RABBITMQ_EXCHANGE", "ws.outbox")
    RABBITMQ_ROUTING_KEY = os.getenv("RABBITMQ_ROUTING_KEY", "ws.outbox")
    RABBITMQ_QUEUE_TTL_MS = int(os.getenv("RABBITMQ_QUEUE_TTL_MS", "0"))
    RABBITMQ_INBOX_EXCHANGE = os.getenv("RABBITMQ_INBOX_EXCHANGE", "ws.inbox")
    RABBITMQ_INBOX_ROUTING_KEY = os.getenv("RABBITMQ_INBOX_ROUTING_KEY", "ws.inbox")
    RABBITMQ_INBOX_QUEUE = os.getenv("RABBITMQ_INBOX_QUEUE", "")
    RABBITMQ_INBOX_QUEUE_TTL_MS = int(os.getenv("RABBITMQ_INBOX_QUEUE_TTL_MS", "0"))
    RABBITMQ_EVENTS_EXCHANGE = os.getenv("RABBITMQ_EVENTS_EXCHANGE", "ws.events")
    RABBITMQ_EVENTS_ROUTING_KEY = os.getenv("RABBITMQ_EVENTS_ROUTING_KEY", "ws.events")
    RABBITMQ_EVENTS_QUEUE = os.getenv("RABBITMQ_EVENTS_QUEUE", "")
    RABBITMQ_EVENTS_QUEUE_TTL_MS = int(os.getenv("RABBITMQ_EVENTS_QUEUE_TTL_MS", "0"))
    RABBITMQ_DLQ_QUEUE = os.getenv("RABBITMQ_DLQ_QUEUE", "ws.dlq")
    RABBITMQ_DLQ_EXCHANGE = os.getenv("RABBITMQ_DLQ_EXCHANGE", "ws.dlq")
    RABBITMQ_REPLAY_TARGET_EXCHANGE = os.getenv("RABBITMQ_REPLAY_TARGET_EXCHANGE", "")
    RABBITMQ_REPLAY_TARGET_ROUTING_KEY = os.getenv("RABBITMQ_REPLAY_TARGET_ROUTING_KEY", "")
    RABBITMQ_REPLAY_MAX_BATCH = int(os.getenv("RABBITMQ_REPLAY_MAX_BATCH", "100"))
    REDIS_DLQ_STREAM = os.getenv("REDIS_DLQ_STREAM", "ws.dlq")
    REDIS_INBOX_STREAM = os.getenv("REDIS_INBOX_STREAM", "ws.inbox")
    REDIS_EVENTS_STREAM = os.getenv("REDIS_EVENTS_STREAM", "ws.events")
    PRESENCE_REDIS_DSN = os.getenv("PRESENCE_REDIS_DSN", REDIS_DSN)
    PRESENCE_REDIS_PREFIX = os.getenv("PRESENCE_REDIS_PREFIX", "presence:")
    PRESENCE_TTL_SECONDS = int(os.getenv("PRESENCE_TTL_SECONDS", "120"))
    PRESENCE_STRATEGY = os.getenv("PRESENCE_STRATEGY", "ttl").lower()
    PRESENCE_HEARTBEAT_SECONDS = int(os.getenv("PRESENCE_HEARTBEAT_SECONDS", "30"))
    PRESENCE_GRACE_SECONDS = int(os.getenv("PRESENCE_GRACE_SECONDS", "15"))
    PRESENCE_REFRESH_ON_MESSAGE = os.getenv("PRESENCE_REFRESH_ON_MESSAGE", "1").lower() in ("1", "true", "yes")
    PRESENCE_REFRESH_MIN_INTERVAL_SECONDS = int(os.getenv("PRESENCE_REFRESH_MIN_INTERVAL_SECONDS", "0"))
    PRESENCE_REFRESH_QUEUE_SIZE = int(os.getenv("PRESENCE_REFRESH_QUEUE_SIZE", "1024"))
    WEBHOOK_RETRY_ATTEMPTS = int(os.getenv("WEBHOOK_RETRY_ATTEMPTS", "3"))
    WEBHOOK_RETRY_BASE_SECONDS = float(os.getenv("WEBHOOK_RETRY_BASE_SECONDS", "0.5"))
    WEBHOOK_TIMEOUT_SECONDS = float(os.getenv("WEBHOOK_TIMEOUT_SECONDS", "5"))
    TRACING_STRATEGY = os.getenv("TRACING_STRATEGY", "none").lower()
    TRACING_TRACE_ID_FIELD = os.getenv("TRACING_TRACE_ID_FIELD", "trace_id")
    TRACING_HEADER_NAME = os.getenv("TRACING_HEADER_NAME", "X-Trace-Id")
    TRACING_SAMPLE_RATE = float(os.getenv("TRACING_SAMPLE_RATE", "1.0"))
    TRACING_EXPORTER = os.getenv("TRACING_EXPORTER", "stdout").lower()
    OTEL_SERVICE_NAME = os.getenv("OTEL_SERVICE_NAME", "gateway")
    OTEL_EXPORTER_OTLP_ENDPOINT = os.getenv("OTEL_EXPORTER_OTLP_ENDPOINT", "")
    OTEL_EXPORTER_OTLP_PROTOCOL = os.getenv("OTEL_EXPORTER_OTLP_PROTOCOL", "http/protobuf").lower()
    REPLAY_STRATEGY = os.getenv("REPLAY_STRATEGY", "none").lower()
    REPLAY_RETENTION_SECONDS = int(os.getenv("REPLAY_RETENTION_SECONDS", "0"))
    REPLAY_MAXLEN = int(os.getenv("REPLAY_MAXLEN", "0"))
    REPLAY_SNAPSHOT_SECONDS = int(os.getenv("REPLAY_SNAPSHOT_SECONDS", "0"))
    REPLAY_API_KEY = os.getenv("REPLAY_API_KEY", "")
    REPLAY_RATE_LIMIT_STRATEGY = os.getenv("REPLAY_RATE_LIMIT_STRATEGY", "in_memory").lower()
    REPLAY_RATE_LIMIT_PER_MINUTE = int(os.getenv("REPLAY_RATE_LIMIT_PER_MINUTE", "10"))
    REPLAY_RATE_LIMIT_WINDOW_SECONDS = int(os.getenv("REPLAY_RATE_LIMIT_WINDOW_SECONDS", "60"))
    REPLAY_RATE_LIMIT_REDIS_DSN = os.getenv("REPLAY_RATE_LIMIT_REDIS_DSN", REDIS_DSN)
    REPLAY_RATE_LIMIT_PREFIX = os.getenv("REPLAY_RATE_LIMIT_PREFIX", "replay:rate:")
    REPLAY_RATE_LIMIT_KEY = os.getenv("REPLAY_RATE_LIMIT_KEY", "api_key_or_ip").lower()
    REPLAY_IDEMPOTENCY_STRATEGY = os.getenv("REPLAY_IDEMPOTENCY_STRATEGY", "none").lower()
    REPLAY_IDEMPOTENCY_TTL_SECONDS = int(os.getenv("REPLAY_IDEMPOTENCY_TTL_SECONDS", "900"))
    REPLAY_IDEMPOTENCY_REDIS_DSN = os.getenv("REPLAY_IDEMPOTENCY_REDIS_DSN", REPLAY_RATE_LIMIT_REDIS_DSN)
    REPLAY_IDEMPOTENCY_PREFIX = os.getenv("REPLAY_IDEMPOTENCY_PREFIX", "replay:idempotency:")
    REPLAY_IDEMPOTENCY_HEADER = os.getenv("REPLAY_IDEMPOTENCY_HEADER", "Idempotency-Key")
    REPLAY_IDEMPOTENCY_PAYLOAD_FIELD = os.getenv("REPLAY_IDEMPOTENCY_PAYLOAD_FIELD", "idempotency_key")
    REPLAY_AUDIT_LOG = os.getenv("REPLAY_AUDIT_LOG", "1").lower() in ("1", "true", "yes", "on")
    WS_RATE_LIMIT_PER_SEC = float(os.getenv("WS_RATE_LIMIT_PER_SEC", "10"))
    WS_RATE_LIMIT_BURST = float(os.getenv("WS_RATE_LIMIT_BURST", "20"))
    BACKPRESSURE_STRATEGY = os.getenv("BACKPRESSURE_STRATEGY", "none").lower()
    BACKPRESSURE_PER_CONN_BUFFER = int(os.getenv("BACKPRESSURE_PER_CONN_BUFFER", "0"))
    BACKPRESSURE_GLOBAL_BUFFER = int(os.getenv("BACKPRESSURE_GLOBAL_BUFFER", "0"))
    BACKPRESSURE_MAX_INFLIGHT = int(os.getenv("BACKPRESSURE_MAX_INFLIGHT", "0"))
    BACKPRESSURE_DROP_POLICY = os.getenv("BACKPRESSURE_DROP_POLICY", "oldest").lower()
    ORDERING_STRATEGY = os.getenv("ORDERING_STRATEGY", "none").lower()
    ORDERING_TOPIC_FIELD = os.getenv("ORDERING_TOPIC_FIELD", "topic")
    ORDERING_SUBJECT_SOURCE = os.getenv("ORDERING_SUBJECT_SOURCE", "user").lower()
    ORDERING_PARTITION_MODE = os.getenv("ORDERING_PARTITION_MODE", "none").lower()
    ORDERING_PARTITION_MAX_LEN = int(os.getenv("ORDERING_PARTITION_MAX_LEN", "64"))
    LOG_FORMAT = os.getenv("LOG_FORMAT", "json")
    LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()

    if TRACING_STRATEGY not in ("none", "propagate", "full"):
        TRACING_STRATEGY = "none"
    if TRACING_SAMPLE_RATE < 0:
        TRACING_SAMPLE_RATE = 0.0
    if TRACING_SAMPLE_RATE > 1:
        TRACING_SAMPLE_RATE = 1.0
    if TRACING_EXPORTER not in ("stdout", "otlp", "none"):
        TRACING_EXPORTER = "stdout"
    if REPLAY_STRATEGY not in ("none", "bounded", "durable"):
        REPLAY_STRATEGY = "none"
    if REPLAY_RETENTION_SECONDS < 0:
        REPLAY_RETENTION_SECONDS = 0
    if REPLAY_MAXLEN < 0:
        REPLAY_MAXLEN = 0
    if REPLAY_SNAPSHOT_SECONDS < 0:
        REPLAY_SNAPSHOT_SECONDS = 0
    if REPLAY_RATE_LIMIT_PER_MINUTE < 0:
        REPLAY_RATE_LIMIT_PER_MINUTE = 0
    if REPLAY_RATE_LIMIT_WINDOW_SECONDS <= 0:
        REPLAY_RATE_LIMIT_WINDOW_SECONDS = 60
    if REPLAY_RATE_LIMIT_STRATEGY not in ("in_memory", "redis", "none"):
        REPLAY_RATE_LIMIT_STRATEGY = "in_memory"
    if REPLAY_RATE_LIMIT_KEY not in ("api_key", "ip", "api_key_or_ip", "api_key_and_ip"):
        REPLAY_RATE_LIMIT_KEY = "api_key_or_ip"
    if REPLAY_IDEMPOTENCY_STRATEGY not in ("none", "in_memory", "redis"):
        REPLAY_IDEMPOTENCY_STRATEGY = "none"
    if REPLAY_IDEMPOTENCY_TTL_SECONDS < 0:
        REPLAY_IDEMPOTENCY_TTL_SECONDS = 0
    if ORDERING_STRATEGY not in ("none", "topic", "subject"):
        ORDERING_STRATEGY = "none"
    if ORDERING_SUBJECT_SOURCE not in ("user", "subject"):
        ORDERING_SUBJECT_SOURCE = "user"
    if ORDERING_PARTITION_MODE not in ("none", "suffix"):
        ORDERING_PARTITION_MODE = "none"
    if PRESENCE_STRATEGY not in ("ttl", "heartbeat", "session"):
        PRESENCE_STRATEGY = "ttl"
    if PRESENCE_HEARTBEAT_SECONDS < 0:
        PRESENCE_HEARTBEAT_SECONDS = 0
    if PRESENCE_GRACE_SECONDS < 0:
        PRESENCE_GRACE_SECONDS = 0
    if PRESENCE_REFRESH_MIN_INTERVAL_SECONDS < 0:
        PRESENCE_REFRESH_MIN_INTERVAL_SECONDS = 0
    if PRESENCE_REFRESH_QUEUE_SIZE < 1:
        PRESENCE_REFRESH_QUEUE_SIZE = 1
    if BACKPRESSURE_STRATEGY not in ("none", "drop", "close", "buffer"):
        BACKPRESSURE_STRATEGY = "none"
    if BACKPRESSURE_DROP_POLICY not in ("oldest", "newest"):
        BACKPRESSURE_DROP_POLICY = "oldest"
    if BACKPRESSURE_PER_CONN_BUFFER < 0:
        BACKPRESSURE_PER_CONN_BUFFER = 0
    if BACKPRESSURE_GLOBAL_BUFFER < 0:
        BACKPRESSURE_GLOBAL_BUFFER = 0
    if BACKPRESSURE_MAX_INFLIGHT < 0:
        BACKPRESSURE_MAX_INFLIGHT = 0

    return Settings(
        JWT_ALG=JWT_ALG,
        JWT_USER_ID_CLAIM=JWT_USER_ID_CLAIM,
        JWT_PUBLIC_KEY=JWT_PUBLIC_KEY,
        JWT_PUBLIC_KEY_FILE=JWT_PUBLIC_KEY_FILE,
        JWT_JWKS_URL=JWT_JWKS_URL,
        JWT_ISSUER=JWT_ISSUER,
        JWT_AUDIENCE=JWT_AUDIENCE,
        JWT_LEEWAY=JWT_LEEWAY,
        WS_MODE=WS_MODE,
        EVENTS_MODE=EVENTS_MODE,
        SYMFONY_WEBHOOK_URL=SYMFONY_WEBHOOK_URL,
        SYMFONY_WEBHOOK_SECRET=SYMFONY_WEBHOOK_SECRET,
        GATEWAY_API_KEY=GATEWAY_API_KEY,
        REDIS_DSN=REDIS_DSN,
        REDIS_STREAM=REDIS_STREAM,
        RABBITMQ_DSN=RABBITMQ_DSN,
        RABBITMQ_QUEUE=RABBITMQ_QUEUE,
        RABBITMQ_EXCHANGE=RABBITMQ_EXCHANGE,
        RABBITMQ_ROUTING_KEY=RABBITMQ_ROUTING_KEY,
        RABBITMQ_QUEUE_TTL_MS=RABBITMQ_QUEUE_TTL_MS,
        RABBITMQ_INBOX_EXCHANGE=RABBITMQ_INBOX_EXCHANGE,
        RABBITMQ_INBOX_ROUTING_KEY=RABBITMQ_INBOX_ROUTING_KEY,
        RABBITMQ_INBOX_QUEUE=RABBITMQ_INBOX_QUEUE,
        RABBITMQ_INBOX_QUEUE_TTL_MS=RABBITMQ_INBOX_QUEUE_TTL_MS,
        RABBITMQ_EVENTS_EXCHANGE=RABBITMQ_EVENTS_EXCHANGE,
        RABBITMQ_EVENTS_ROUTING_KEY=RABBITMQ_EVENTS_ROUTING_KEY,
        RABBITMQ_EVENTS_QUEUE=RABBITMQ_EVENTS_QUEUE,
        RABBITMQ_EVENTS_QUEUE_TTL_MS=RABBITMQ_EVENTS_QUEUE_TTL_MS,
        RABBITMQ_DLQ_QUEUE=RABBITMQ_DLQ_QUEUE,
        RABBITMQ_DLQ_EXCHANGE=RABBITMQ_DLQ_EXCHANGE,
        RABBITMQ_REPLAY_TARGET_EXCHANGE=RABBITMQ_REPLAY_TARGET_EXCHANGE,
        RABBITMQ_REPLAY_TARGET_ROUTING_KEY=RABBITMQ_REPLAY_TARGET_ROUTING_KEY,
        RABBITMQ_REPLAY_MAX_BATCH=RABBITMQ_REPLAY_MAX_BATCH,
        REDIS_DLQ_STREAM=REDIS_DLQ_STREAM,
        REDIS_INBOX_STREAM=REDIS_INBOX_STREAM,
        REDIS_EVENTS_STREAM=REDIS_EVENTS_STREAM,
        PRESENCE_REDIS_DSN=PRESENCE_REDIS_DSN,
        PRESENCE_REDIS_PREFIX=PRESENCE_REDIS_PREFIX,
        PRESENCE_TTL_SECONDS=PRESENCE_TTL_SECONDS,
        PRESENCE_STRATEGY=PRESENCE_STRATEGY,
        PRESENCE_HEARTBEAT_SECONDS=PRESENCE_HEARTBEAT_SECONDS,
        PRESENCE_GRACE_SECONDS=PRESENCE_GRACE_SECONDS,
        PRESENCE_REFRESH_ON_MESSAGE=PRESENCE_REFRESH_ON_MESSAGE,
        PRESENCE_REFRESH_MIN_INTERVAL_SECONDS=PRESENCE_REFRESH_MIN_INTERVAL_SECONDS,
        PRESENCE_REFRESH_QUEUE_SIZE=PRESENCE_REFRESH_QUEUE_SIZE,
        WEBHOOK_RETRY_ATTEMPTS=WEBHOOK_RETRY_ATTEMPTS,
        WEBHOOK_RETRY_BASE_SECONDS=WEBHOOK_RETRY_BASE_SECONDS,
        WEBHOOK_TIMEOUT_SECONDS=WEBHOOK_TIMEOUT_SECONDS,
        TRACING_STRATEGY=TRACING_STRATEGY,
        TRACING_TRACE_ID_FIELD=TRACING_TRACE_ID_FIELD,
        TRACING_HEADER_NAME=TRACING_HEADER_NAME,
        TRACING_SAMPLE_RATE=TRACING_SAMPLE_RATE,
        TRACING_EXPORTER=TRACING_EXPORTER,
        OTEL_SERVICE_NAME=OTEL_SERVICE_NAME,
        OTEL_EXPORTER_OTLP_ENDPOINT=OTEL_EXPORTER_OTLP_ENDPOINT,
        OTEL_EXPORTER_OTLP_PROTOCOL=OTEL_EXPORTER_OTLP_PROTOCOL,
        REPLAY_STRATEGY=REPLAY_STRATEGY,
        REPLAY_RETENTION_SECONDS=REPLAY_RETENTION_SECONDS,
        REPLAY_MAXLEN=REPLAY_MAXLEN,
        REPLAY_SNAPSHOT_SECONDS=REPLAY_SNAPSHOT_SECONDS,
        REPLAY_API_KEY=REPLAY_API_KEY,
        REPLAY_RATE_LIMIT_STRATEGY=REPLAY_RATE_LIMIT_STRATEGY,
        REPLAY_RATE_LIMIT_PER_MINUTE=REPLAY_RATE_LIMIT_PER_MINUTE,
        REPLAY_RATE_LIMIT_WINDOW_SECONDS=REPLAY_RATE_LIMIT_WINDOW_SECONDS,
        REPLAY_RATE_LIMIT_REDIS_DSN=REPLAY_RATE_LIMIT_REDIS_DSN,
        REPLAY_RATE_LIMIT_PREFIX=REPLAY_RATE_LIMIT_PREFIX,
        REPLAY_RATE_LIMIT_KEY=REPLAY_RATE_LIMIT_KEY,
        REPLAY_IDEMPOTENCY_STRATEGY=REPLAY_IDEMPOTENCY_STRATEGY,
        REPLAY_IDEMPOTENCY_TTL_SECONDS=REPLAY_IDEMPOTENCY_TTL_SECONDS,
        REPLAY_IDEMPOTENCY_REDIS_DSN=REPLAY_IDEMPOTENCY_REDIS_DSN,
        REPLAY_IDEMPOTENCY_PREFIX=REPLAY_IDEMPOTENCY_PREFIX,
        REPLAY_IDEMPOTENCY_HEADER=REPLAY_IDEMPOTENCY_HEADER,
        REPLAY_IDEMPOTENCY_PAYLOAD_FIELD=REPLAY_IDEMPOTENCY_PAYLOAD_FIELD,
        REPLAY_AUDIT_LOG=REPLAY_AUDIT_LOG,
        WS_RATE_LIMIT_PER_SEC=WS_RATE_LIMIT_PER_SEC,
        WS_RATE_LIMIT_BURST=WS_RATE_LIMIT_BURST,
        BACKPRESSURE_STRATEGY=BACKPRESSURE_STRATEGY,
        BACKPRESSURE_PER_CONN_BUFFER=BACKPRESSURE_PER_CONN_BUFFER,
        BACKPRESSURE_GLOBAL_BUFFER=BACKPRESSURE_GLOBAL_BUFFER,
        BACKPRESSURE_MAX_INFLIGHT=BACKPRESSURE_MAX_INFLIGHT,
        BACKPRESSURE_DROP_POLICY=BACKPRESSURE_DROP_POLICY,
        ORDERING_STRATEGY=ORDERING_STRATEGY,
        ORDERING_TOPIC_FIELD=ORDERING_TOPIC_FIELD,
        ORDERING_SUBJECT_SOURCE=ORDERING_SUBJECT_SOURCE,
        ORDERING_PARTITION_MODE=ORDERING_PARTITION_MODE,
        ORDERING_PARTITION_MAX_LEN=ORDERING_PARTITION_MAX_LEN,
        LOG_FORMAT=LOG_FORMAT,
        LOG_LEVEL=LOG_LEVEL,
    )
